### ISSUE TITLE
One character omission

### ISSUE THREAD

**Issue by Honoka55** [dahlia/cjk-compsci-terms#13]
![KkbcK.png](https://s1.328888.xyz/2022/09/12/KkbcK.png)

First result of zh-CN for “bug” should be “漏洞” ([here](https://github.com/dahlia/cjk-compsci-terms/blob/main/tables/programming.yaml#L56)) .The character “洞” disappears. Reproducible in multiple environments.

**Comment by dahlia** [comment]
It's apparently due to a missing space between pinyin *lòu* and *dòng*.  I'm going to fix it ASAP.

**Comment by dahlia** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/12431/189657051-b501c0d1-14f9-40b9-bc83-2b87061533d4.png">

It's now fixed.  Thanks for your reporting!
