### ISSUE TITLE
Interested in contributing to another project?

### ISSUE THREAD

**Issue by GrimPixel** [dahlia/cjk-compsci-terms#16]
I have a repository that contains over two thousand entries, covering concepts from the primary education to the secondary education, as well as some in the tertiary education. My own ability is limited, so I would like to ask if you are glad to contribute.

**Comment by dahlia** [comment]
I've been looking at [your repository][1] with interest.  I see some overlap in goals, but also some differences. This project is not just about creating a table of translations of terms by language; another goal is to visualize how the terms relate to each other.  At the moment, I'm not really focused on this project either.  Perhaps if I ever get some spare time, I won't be able to contribute to your project, but thanks for the offer.

[1]: https://github.com/GrimPixel/SciTech_Index
