### ISSUE TITLE
Possible False Data Report

### ISSUE THREAD

**Issue by TNTErick** [dahlia/cjk-compsci-terms#4]
imho I see the HK word for Application software is written 應用程式 but read 應用程**序(zeoi6)**. 式 should be something like sik1 or sek1.

**Comment by dahlia** [comment]
Thank you for reporting!  I just fixed the typo.

![](https://user-images.githubusercontent.com/12431/147448613-dbcc5eb9-cdb2-4e6d-a4b3-2bd571386f0b.png)
